name: Test and README

on:
  push:
  pull_request:

jobs:
  build:
    name: Fix Readme
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: pip3 -r requirements.txt
      - name: Run script
        run: |
          python3 test+readme.py
      - name: Push
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)  # Only runs if this CI was triggered by the default branch
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "chore(docs): Update README.md" || exit 0   # do not error if nothing to commit
          git push